name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # TODO: Add native build testing later.
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        jdk: [21]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '${{ matrix.jdk }}'
        distribution: 'temurin'
        check-latest: true
        cache: maven
    - name: Build with Maven
      run: mvn -B clean verify package --file pom.xml
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
